version: '3.4'



 



networks:

  dockerapi-dev:

    driver: bridge



 



services:



 



  postgres_image:

    image: postgres:latest

    ports:

      - 5432

    restart: always

    volumes:

      - db_volume:/var/lib/postgresql/data

    environment:

      POSTGRES_USER: "postgres"

      POSTGRES_PASSWORD: "password"

      POSTGRES_DB: "ContactApplicationDB4"

    networks:

      - dockerapi-dev



 



  ContactApplication:

    image: 1998priya/contactappbackend

    depends_on:

      - "postgres_image"

    build:

      context: .

      dockerfile: Dockerfile

    environment:

      DBServer: "postgres_image"

    ports:

      - 80:80

    networks:

      - dockerapi-dev

volumes:

  db_volume: